<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-12-19T22:16:00Z" name="Default suite" finished-at="2020-12-19T22:16:23Z" duration-ms="22571">
    <groups>
    </groups>
    <test started-at="2020-12-19T22:16:00Z" name="Default test" finished-at="2020-12-19T22:16:23Z" duration-ms="22571">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:00Z" name="beforeMethod" finished-at="2020-12-19T17:16:07Z" duration-ms="6840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="LoginWrongEmailTest()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:07Z" name="LoginWrongEmailTest" finished-at="2020-12-19T17:16:10Z" duration-ms="2603" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sorry, we don't recognize this email.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sorry, we don't recognize this email.] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at tests.LoginTest.LoginWrongEmailTest(LoginTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWrongEmailTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:10Z" name="afterMethod" finished-at="2020-12-19T17:16:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:10Z" name="beforeMethod" finished-at="2020-12-19T17:16:16Z" duration-ms="6106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="LoginWrongPasswordTest()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:16Z" name="LoginWrongPasswordTest" finished-at="2020-12-19T17:16:23Z" duration-ms="6997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWrongPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.LoginTest@29f69090]" started-at="2020-12-19T17:16:23Z" name="afterMethod" finished-at="2020-12-19T17:16:23Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
